app = "flywp"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  WP_ENVIRONMENT_TYPE = "production"
  WP_DEBUG = "false"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 100

[[mounts]]
  source = "wp_uploads"
  destination = "/var/www/html/wp-content/uploads"

[checks]
  [checks.wordpress_health]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "get"
    path = "/wp-admin/admin-ajax.php"
    port = 80
    timeout = "5s"