[build]
buildCommand = "./build-themes.sh"

[deploy]
healthcheckPath = "/health.php"
healthcheckTimeout = 300

[environments.production]
variables.WP_ENVIRONMENT_TYPE = "production"
variables.WP_DEBUG = "false"