[build]
buildCommand = "./build-themes.sh"

[deploy]
healthcheckPath = "/wp-admin/admin-ajax.php"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production]
variables.WP_ENVIRONMENT_TYPE = "production"
variables.WP_DEBUG = "false"