name: Build Themes & Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, zip

      # Build all themes dynamically
      - name: Build All Themes
        run: |
          # Make build script executable
          chmod +x build-themes.sh

          # Run the build script
          ./build-themes.sh

      # Clean up development files for Railway deployment
      - name: Clean build artifacts
        run: |
          find . -name "*.map" -delete
          find . -name "webpack.*.js" -delete
          find . -name "vite.*.js" -delete
          find . -name "tailwind.*.js" -delete
          find . -name ".git*" -not -name ".github" -delete
          # Keep package.json and composer.json files as they might be needed for Railway
          # Remove node_modules which should already be removed by theme builds
          find . -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true

      # Deploy to Railway
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@v1.1.0
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_ID || 'wordpress-app' }}
          detach: false