name: Build Themes & Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, zip

      # Build Sage Theme
      - name: Build Sage Theme
        run: |
          if [ -d "wp-content/themes/sage" ]; then
            cd wp-content/themes/sage
            npm ci --production=false
            if [ -f "composer.json" ]; then
              composer install --no-dev --optimize-autoloader
            fi
            npm run build
            rm -rf node_modules resources/css resources/js resources/images resources/fonts
          fi

      # Build other themes if they exist
      - name: Build Additional Themes
        run: |
          for theme_dir in wp-content/themes/*/; do
            if [ -f "${theme_dir}package.json" ] && [ "${theme_dir}" != "wp-content/themes/sage/" ]; then
              echo "Building theme: ${theme_dir}"
              cd "${theme_dir}"
              npm ci --production=false
              if [ -f "composer.json" ]; then
                composer install --no-dev --optimize-autoloader
              fi
              if npm run | grep -q "build"; then
                npm run build
              fi
              rm -rf node_modules src resources
              cd - > /dev/null
            fi
          done

      # Clean up development files for Railway deployment
      - name: Clean build artifacts
        run: |
          find . -name "*.map" -delete
          find . -name "webpack.*.js" -delete
          find . -name "vite.*.js" -delete
          find . -name "tailwind.*.js" -delete
          find . -name ".git*" -not -name ".github" -delete
          find . -name "README.md" -not -path "./README.md" -delete

      # Deploy to Railway
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@v1.1.0
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_ID || 'wordpress-app' }}
          detach: false